const groceryItems = [
  {
    id: 1,
    title: "Organic Apple",
    brand: "Nature's Best",
    quantities: [
      { amount: "500g", price: 3.49 },
      { amount: "1kg", price: 6.49 },
    ],
    tags: ["fruit", "organic", "healthy"],
    image: "https://example.com/images/organic-apple.jpg",
  },
  {
    id: 2,
    title: "Red Apple",
    brand: "Apple Farms",
    quantities: [
      { amount: "250g", price: 1.99 },
      { amount: "500g", price: 3.49 },
    ],
    tags: ["fruit", "fresh", "snack"],
    image: "https://example.com/images/red-apple.jpg",
  },
  {
    id: 3,
    title: "Whole Wheat Bread",
    brand: "Healthy Grains",
    quantities: [
      { amount: "500g", price: 2.29 },
      { amount: "1kg", price: 4.49 },
    ],
    tags: ["bread", "whole wheat", "fiber"],
    image: "https://example.com/images/whole-wheat-bread.jpg",
  },
  {
    id: 4,
    title: "Multigrain Bread",
    brand: "Bread Masters",
    quantities: [
      { amount: "250g", price: 1.99 },
      { amount: "500g", price: 3.29 },
    ],
    tags: ["bread", "multigrain", "healthy"],
    image: "https://example.com/images/multigrain-bread.jpg",
  },
  {
    id: 5,
    title: "Almond Milk",
    brand: "Nutty Bliss",
    quantities: [
      { amount: "1L", price: 4.49 },
      { amount: "500ml", price: 2.49 },
    ],
    tags: ["dairy-free", "vegan", "healthy"],
    image: "https://example.com/images/almond-milk.jpg",
  },
  {
    id: 6,
    title: "Soy Milk",
    brand: "Soy Fresh",
    quantities: [
      { amount: "1L", price: 3.99 },
      { amount: "2L", price: 7.49 },
    ],
    tags: ["dairy-free", "plant-based", "healthy"],
    image: "https://example.com/images/soy-milk.jpg",
  },
  {
    id: 7,
    title: "Brown Rice",
    brand: "Golden Harvest",
    quantities: [
      { amount: "1kg", price: 2.49 },
      { amount: "2kg", price: 4.49 },
    ],
    tags: ["grain", "fiber", "healthy"],
    image: "https://example.com/images/brown-rice.jpg",
  },
  {
    id: 8,
    title: "White Rice",
    brand: "Rice Delight",
    quantities: [
      { amount: "1kg", price: 3.49 },
      { amount: "5kg", price: 14.99 },
    ],
    tags: ["grain", "staple", "cooking"],
    image: "https://example.com/images/white-rice.jpg",
  },
  {
    id: 9,
    title: "Olive Oil",
    brand: "Mediterranean Gold",
    quantities: [
      { amount: "500ml", price: 5.49 },
      { amount: "1L", price: 9.99 },
    ],
    tags: ["oil", "healthy fats", "cooking"],
    image: "https://example.com/images/olive-oil.jpg",
  },
  {
    id: 10,
    title: "Canola Oil",
    brand: "Pure Harvest",
    quantities: [
      { amount: "1L", price: 6.49 },
      { amount: "2L", price: 11.49 },
    ],
    tags: ["oil", "cooking", "low-fat"],
    image: "https://example.com/images/canola-oil.jpg",
  },
  {
    id: 11,
    title: "Peanut Butter",
    brand: "Nutty Goodness",
    quantities: [
      { amount: "250g", price: 3.49 },
      { amount: "500g", price: 5.99 },
    ],
    tags: ["spread", "high protein", "snack"],
    image: "https://example.com/images/peanut-butter.jpg",
  },
  {
    id: 12,
    title: "Almond Butter",
    brand: "NutriSpread",
    quantities: [
      { amount: "250g", price: 4.49 },
      { amount: "300g", price: 5.49 },
    ],
    tags: ["spread", "vegan", "healthy fats"],
    image: "https://example.com/images/almond-butter.jpg",
  },
  {
    id: 13,
    title: "Chia Seeds",
    brand: "SuperFoods",
    quantities: [
      { amount: "200g", price: 4.99 },
      { amount: "500g", price: 8.99 },
    ],
    tags: ["seeds", "high fiber", "superfood"],
    image: "https://example.com/images/chia-seeds.jpg",
  },
  {
    id: 14,
    title: "Flax Seeds",
    brand: "Nutri Seeds",
    quantities: [
      { amount: "150g", price: 3.99 },
      { amount: "500g", price: 6.99 },
    ],
    tags: ["seeds", "high fiber", "healthy"],
    image: "https://example.com/images/flax-seeds.jpg",
  },
  {
    id: 15,
    title: "Greek Yogurt",
    brand: "Yogurt Bliss",
    quantities: [
      { amount: "250g", price: 2.99 },
      { amount: "500g", price: 4.99 },
    ],
    tags: ["yogurt", "probiotic", "snack"],
    image: "https://example.com/images/greek-yogurt.jpg",
  },
  {
    id: 16,
    title: "Low-Fat Yogurt",
    brand: "Dairy Delight",
    quantities: [
      { amount: "200g", price: 2.49 },
      { amount: "400g", price: 3.99 },
    ],
    tags: ["yogurt", "low-fat", "snack"],
    image: "https://example.com/images/low-fat-yogurt.jpg",
  },
  {
    id: 17,
    title: "Spinach",
    brand: "Fresh Farm",
    quantities: [
      { amount: "250g", price: 1.99 },
      { amount: "500g", price: 3.49 },
    ],
    tags: ["vegetable", "organic", "green"],
    image: "https://example.com/images/spinach.jpg",
  },
  {
    id: 18,
    title: "Kale",
    brand: "Green Leaf",
    quantities: [
      { amount: "250g", price: 2.49 },
      { amount: "500g", price: 4.49 },
    ],
    tags: ["vegetable", "superfood", "fiber"],
    image: "https://example.com/images/kale.jpg",
  },
  {
    id: 19,
    title: "Eggs",
    brand: "Farm Fresh",
    quantities: [
      { amount: "12 pack", price: 3.49 },
      { amount: "6 pack", price: 2.49 },
    ],
    tags: ["protein", "dairy", "organic"],
    image: "https://example.com/images/eggs.jpg",
  },
  {
    id: 20,
    title: "Free-Range Eggs",
    brand: "Happy Hens",
    quantities: [
      { amount: "12 pack", price: 4.49 },
      { amount: "6 pack", price: 3.49 },
    ],
    tags: ["protein", "dairy", "free-range"],
    image: "https://example.com/images/free-range-eggs.jpg",
  },
  {
    id: 21,
    title: "Tomato Ketchup",
    brand: "Tomato Delight",
    quantities: [
      { amount: "500ml", price: 2.49 },
      { amount: "1L", price: 4.49 },
    ],
    tags: ["condiment", "sauce", "snack"],
    image: "https://example.com/images/tomato-ketchup.jpg",
  },
  {
    id: 22,
    title: "Chili Sauce",
    brand: "Spicy Delight",
    quantities: [
      { amount: "250ml", price: 2.49 },
      { amount: "500ml", price: 4.49 },
    ],
    tags: ["condiment", "sauce", "spicy"],
    image: "https://example.com/images/chili-sauce.jpg",
  },
  {
    id: 23,
    title: "Oregano",
    brand: "Herb Garden",
    quantities: [
      { amount: "50g", price: 1.99 },
      { amount: "100g", price: 3.49 },
    ],
    tags: ["spice", "herb", "cooking"],
    image: "https://example.com/images/oregano.jpg",
  },
  {
    id: 24,
    title: "Basil",
    brand: "Herb Master",
    quantities: [
      { amount: "50g", price: 1.99 },
      { amount: "100g", price: 3.49 },
    ],
    tags: ["spice", "herb", "cooking"],
    image: "https://example.com/images/basil.jpg",
  },
  {
    id: 25,
    title: "Black Pepper",
    brand: "Spice World",
    quantities: [
      { amount: "100g", price: 1.99 },
      { amount: "250g", price: 3.49 },
    ],
    tags: ["spice", "flavor", "cooking"],
    image: "https://example.com/images/black-pepper.jpg",
  },
  {
    id: 26,
    title: "Green Tea",
    brand: "Tea Time",
    quantities: [
      { amount: "20 bags", price: 2.49 },
      { amount: "40 bags", price: 4.49 },
    ],
    tags: ["tea", "herbal", "healthy"],
    image: "https://example.com/images/green-tea.jpg",
  },
  {
    id: 27,
    title: "Coffee",
    brand: "Café Aroma",
    quantities: [
      { amount: "250g", price: 4.99 },
      { amount: "500g", price: 8.99 },
    ],
    tags: ["coffee", "beverage", "energy"],
    image: "https://example.com/images/coffee.jpg",
  },
  {
    id: 28,
    title: "Dark Chocolate",
    brand: "Sweet Indulgence",
    quantities: [
      { amount: "100g", price: 2.49 },
      { amount: "200g", price: 4.49 },
    ],
    tags: ["snack", "chocolate", "sweet"],
    image: "https://example.com/images/dark-chocolate.jpg",
  },
  {
    id: 29,
    title: "Granola Bar",
    brand: "Healthy Snack",
    quantities: [
      { amount: "6 pack", price: 3.99 },
      { amount: "12 pack", price: 6.99 },
    ],
    tags: ["snack", "healthy", "energy"],
    image: "https://example.com/images/granola-bar.jpg",
  },
  {
    id: 30,
    title: "Protein Powder",
    brand: "Fitness Fuel",
    quantities: [
      { amount: "500g", price: 29.99 },
      { amount: "1kg", price: 49.99 },
    ],
    tags: ["protein", "supplement", "fitness"],
    image: "https://example.com/images/protein-powder.jpg",
  },
  {
    id: 31,
    title: "Vegan Protein Powder",
    brand: "Plant Power",
    quantities: [
      { amount: "500g", price: 34.99 },
      { amount: "1kg", price: 59.99 },
    ],
    tags: ["protein", "vegan", "supplement"],
    image: "https://example.com/images/vegan-protein-powder.jpg",
  },
  {
    id: 32,
    title: "Coconut Water",
    brand: "Tropical Fresh",
    quantities: [
      { amount: "500ml", price: 2.99 },
      { amount: "1L", price: 4.99 },
    ],
    tags: ["beverage", "healthy", "refreshing"],
    image: "https://example.com/images/coconut-water.jpg",
  },
  {
    id: 33,
    title: "Energy Drink",
    brand: "Boost Up",
    quantities: [
      { amount: "250ml", price: 1.49 },
      { amount: "500ml", price: 2.49 },
    ],
    tags: ["beverage", "energy", "refreshing"],
    image: "https://example.com/images/energy-drink.jpg",
  },
  {
    id: 34,
    title: "Bottled Water",
    brand: "Pure Water",
    quantities: [
      { amount: "500ml", price: 0.99 },
      { amount: "1L", price: 1.49 },
    ],
    tags: ["beverage", "hydration", "refreshing"],
    image: "https://example.com/images/bottled-water.jpg",
  },
  {
    id: 35,
    title: "Frozen Vegetables",
    brand: "Green Freezer",
    quantities: [
      { amount: "500g", price: 2.99 },
      { amount: "1kg", price: 4.99 },
    ],
    tags: ["vegetable", "frozen", "healthy"],
    image: "https://example.com/images/frozen-vegetables.jpg",
  },
  {
    id: 36,
    title: "Frozen Fruits",
    brand: "Tropical Freezer",
    quantities: [
      { amount: "500g", price: 3.49 },
      { amount: "1kg", price: 5.49 },
    ],
    tags: ["fruit", "frozen", "healthy"],
    image: "https://example.com/images/frozen-fruits.jpg",
  },
  {
    id: 37,
    title: "Snack Chips",
    brand: "Crispy Treats",
    quantities: [
      { amount: "200g", price: 1.99 },
      { amount: "500g", price: 3.49 },
    ],
    tags: ["snack", "crispy", "savory"],
    image: "https://example.com/images/snack-chips.jpg",
  },
  {
    id: 38,
    title: "Rice Crackers",
    brand: "Crunchy Bites",
    quantities: [
      { amount: "100g", price: 2.49 },
      { amount: "200g", price: 3.49 },
    ],
    tags: ["snack", "gluten-free", "healthy"],
    image: "https://example.com/images/rice-crackers.jpg",
  },
  {
    id: 39,
    title: "Soda",
    brand: "Fizzy Drink",
    quantities: [
      { amount: "500ml", price: 1.49 },
      { amount: "1L", price: 2.49 },
    ],
    tags: ["beverage", "refreshing", "sweet"],
    image: "https://example.com/images/soda.jpg",
  },
  {
    id: 40,
    title: "Fruit Juice",
    brand: "Juice World",
    quantities: [
      { amount: "500ml", price: 2.49 },
      { amount: "1L", price: 3.99 },
    ],
    tags: ["beverage", "fruit", "refreshing"],
    image: "https://example.com/images/fruit-juice.jpg",
  },
];

export default groceryItems;
