const groceryItems = [
  {
    title: "Organic Apple",
    brand: "Nature's Best",
    quantities: ["500g", "1kg"],
    tags: ["fruit", "organic", "healthy"],
    price: 3.99,
    image: "https://example.com/images/organic-apple.jpg",
  },
  {
    title: "Red Apple",
    brand: "Apple Farms",
    quantities: ["250g", "500g"],
    tags: ["fruit", "fresh", "snack"],
    price: 2.99,
    image: "https://example.com/images/red-apple.jpg",
  },
  {
    title: "Whole Wheat Bread",
    brand: "Healthy Grains",
    quantities: ["500g", "1kg"],
    tags: ["bread", "whole wheat", "fiber"],
    price: 2.49,
    image: "https://example.com/images/whole-wheat-bread.jpg",
  },
  {
    title: "Multigrain Bread",
    brand: "Bread Masters",
    quantities: ["250g", "500g"],
    tags: ["bread", "multigrain", "healthy"],
    price: 2.79,
    image: "https://example.com/images/multigrain-bread.jpg",
  },
  {
    title: "Almond Milk",
    brand: "Nutty Bliss",
    quantities: ["1L", "500ml"],
    tags: ["dairy-free", "vegan", "healthy"],
    price: 4.99,
    image: "https://example.com/images/almond-milk.jpg",
  },
  {
    title: "Soy Milk",
    brand: "Soy Fresh",
    quantities: ["1L", "2L"],
    tags: ["dairy-free", "plant-based", "healthy"],
    price: 3.99,
    image: "https://example.com/images/soy-milk.jpg",
  },
  {
    title: "Brown Rice",
    brand: "Golden Harvest",
    quantities: ["1kg", "2kg"],
    tags: ["grain", "fiber", "healthy"],
    price: 2.99,
    image: "https://example.com/images/brown-rice.jpg",
  },
  {
    title: "White Rice",
    brand: "Rice Delight",
    quantities: ["1kg", "5kg"],
    tags: ["grain", "staple", "cooking"],
    price: 3.49,
    image: "https://example.com/images/white-rice.jpg",
  },
  {
    title: "Olive Oil",
    brand: "Mediterranean Gold",
    quantities: ["500ml", "1L"],
    tags: ["oil", "healthy fats", "cooking"],
    price: 7.99,
    image: "https://example.com/images/olive-oil.jpg",
  },
  {
    title: "Canola Oil",
    brand: "Pure Harvest",
    quantities: ["1L", "2L"],
    tags: ["oil", "cooking", "low-fat"],
    price: 6.99,
    image: "https://example.com/images/canola-oil.jpg",
  },
  {
    title: "Peanut Butter",
    brand: "Nutty Goodness",
    quantities: ["250g", "500g"],
    tags: ["spread", "high protein", "snack"],
    price: 5.49,
    image: "https://example.com/images/peanut-butter.jpg",
  },
  {
    title: "Almond Butter",
    brand: "NutriSpread",
    quantities: ["250g", "300g"],
    tags: ["spread", "vegan", "healthy fats"],
    price: 6.99,
    image: "https://example.com/images/almond-butter.jpg",
  },
  {
    title: "Chia Seeds",
    brand: "SuperFoods",
    quantities: ["200g", "500g"],
    tags: ["seeds", "high fiber", "superfood"],
    price: 6.99,
    image: "https://example.com/images/chia-seeds.jpg",
  },
  {
    title: "Flax Seeds",
    brand: "Nutri Seeds",
    quantities: ["150g", "500g"],
    tags: ["seeds", "high fiber", "healthy"],
    price: 5.99,
    image: "https://example.com/images/flax-seeds.jpg",
  },
  {
    title: "Greek Yogurt",
    brand: "Yogurt Bliss",
    quantities: ["250g", "500g"],
    tags: ["yogurt", "probiotic", "snack"],
    price: 3.29,
    image: "https://example.com/images/greek-yogurt.jpg",
  },
  {
    title: "Low-Fat Yogurt",
    brand: "Dairy Delight",
    quantities: ["200g", "400g"],
    tags: ["yogurt", "low-fat", "snack"],
    price: 2.99,
    image: "https://example.com/images/low-fat-yogurt.jpg",
  },
  {
    title: "Spinach",
    brand: "Fresh Farm",
    quantities: ["250g", "500g"],
    tags: ["vegetable", "organic", "green"],
    price: 2.79,
    image: "https://example.com/images/spinach.jpg",
  },
  {
    title: "Kale",
    brand: "Green Leaf",
    quantities: ["250g", "500g"],
    tags: ["vegetable", "superfood", "fiber"],
    price: 3.19,
    image: "https://example.com/images/kale.jpg",
  },
  {
    title: "Eggs",
    brand: "Farm Fresh",
    quantities: ["12 pack", "6 pack"],
    tags: ["protein", "dairy", "organic"],
    price: 3.99,
    image: "https://example.com/images/eggs.jpg",
  },
  {
    title: "Free-Range Eggs",
    brand: "Happy Hens",
    quantities: ["12 pack", "6 pack"],
    tags: ["protein", "dairy", "free-range"],
    price: 4.49,
    image: "https://example.com/images/free-range-eggs.jpg",
  },
  {
    title: "Tomato Ketchup",
    brand: "Tomato Delight",
    quantities: ["500ml", "1L"],
    tags: ["condiment", "sauce", "snack"],
    price: 2.99,
    image: "https://example.com/images/tomato-ketchup.jpg",
  },
  {
    title: "Chili Sauce",
    brand: "Spicy Delight",
    quantities: ["250ml", "500ml"],
    tags: ["condiment", "sauce", "spicy"],
    price: 3.19,
    image: "https://example.com/images/chili-sauce.jpg",
  },
  {
    title: "Instant Coffee",
    brand: "Quick Brew",
    quantities: ["100g", "200g"],
    tags: ["coffee", "beverage", "caffeine"],
    price: 5.99,
    image: "https://example.com/images/instant-coffee.jpg",
  },
  {
    title: "Ground Coffee",
    brand: "Coffee World",
    quantities: ["250g", "500g"],
    tags: ["coffee", "beverage", "caffeine"],
    price: 6.99,
    image: "https://example.com/images/ground-coffee.jpg",
  },
  {
    title: "Dark Chocolate",
    brand: "Cocoa Bliss",
    quantities: ["100g", "200g"],
    tags: ["chocolate", "snack", "antioxidants"],
    price: 4.49,
    image: "https://example.com/images/dark-chocolate.jpg",
  },
  {
    title: "Milk Chocolate",
    brand: "Sweet Treats",
    quantities: ["100g", "250g"],
    tags: ["chocolate", "sweet", "snack"],
    price: 3.99,
    image: "https://example.com/images/milk-chocolate.jpg",
  },
  {
    title: "Basmati Rice",
    brand: "Royal Grains",
    quantities: ["1kg", "5kg"],
    tags: ["rice", "grain", "staple"],
    price: 10.99,
    image: "https://example.com/images/basmati-rice.jpg",
  },
  {
    title: "Sushi Rice",
    brand: "Asian Harvest",
    quantities: ["1kg", "2kg"],
    tags: ["rice", "grain", "specialty"],
    price: 12.99,
    image: "https://example.com/images/sushi-rice.jpg",
  },
  {
    title: "Honey",
    brand: "Bee Natural",
    quantities: ["250g", "500g"],
    tags: ["sweetener", "natural", "healthy"],
    price: 6.49,
    image: "https://example.com/images/honey.jpg",
  },
  {
    title: "Maple Syrup",
    brand: "Sweet Maple",
    quantities: ["250ml", "500ml"],
    tags: ["sweetener", "organic", "pancakes"],
    price: 8.99,
    image: "https://example.com/images/maple-syrup.jpg",
  },
  {
    title: "Green Tea",
    brand: "Pure Herbs",
    quantities: ["50 bags", "100 bags"],
    tags: ["tea", "antioxidant", "beverage"],
    price: 8.99,
    image: "https://example.com/images/green-tea.jpg",
  },
  {
    title: "Chamomile Tea",
    brand: "Herbal Harmony",
    quantities: ["50 bags", "100 bags"],
    tags: ["tea", "herbal", "relax"],
    price: 9.49,
    image: "https://example.com/images/chamomile-tea.jpg",
  },
  {
    title: "Pasta",
    brand: "Italiano",
    quantities: ["500g", "1kg"],
    tags: ["pasta", "italian", "staple"],
    price: 3.99,
    image: "https://example.com/images/pasta.jpg",
  },
  {
    title: "Spaghetti",
    brand: "Pasta World",
    quantities: ["500g", "1kg"],
    tags: ["pasta", "italian", "staple"],
    price: 4.49,
    image: "https://example.com/images/spaghetti.jpg",
  },
  {
    title: "Cheddar Cheese",
    brand: "Dairy Delight",
    quantities: ["200g", "500g"],
    tags: ["cheese", "dairy", "snack"],
    price: 4.79,
    image: "https://example.com/images/cheddar-cheese.jpg",
  },
  {
    title: "Mozzarella Cheese",
    brand: "Cheesy Goodness",
    quantities: ["200g", "400g"],
    tags: ["cheese", "pizza", "dairy"],
    price: 5.29,
    image: "https://example.com/images/mozzarella-cheese.jpg",
  },
  {
    title: "Almonds",
    brand: "Nuts Galore",
    quantities: ["100g", "250g"],
    tags: ["nuts", "snack", "protein"],
    price: 7.99,
    image: "https://example.com/images/almonds.jpg",
  },
  {
    title: "Cashews",
    brand: "Nutty Bites",
    quantities: ["100g", "250g"],
    tags: ["nuts", "snack", "healthy fats"],
    price: 6.99,
    image: "https://example.com/images/cashews.jpg",
  },
  {
    title: "Broccoli",
    brand: "Green Garden",
    quantities: ["250g", "500g"],
    tags: ["vegetable", "organic", "green"],
    price: 3.49,
    image: "https://example.com/images/broccoli.jpg",
  },
  {
    title: "Cauliflower",
    brand: "Garden Fresh",
    quantities: ["500g", "1kg"],
    tags: ["vegetable", "organic", "cruciferous"],
    price: 3.99,
    image: "https://example.com/images/cauliflower.jpg",
  },
];

export default groceryItems;
